
spring:
  application:
    name: SpringData

  datasource:
    password: Incorrect@7
    url: jdbc:postgresql://localhost:9090/SpringDDB
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


  sql:
    init:
      mode: always


  main:
    allow-bean-definition-overriding: true

  #  web:
  #    resources:
  #      static-locations: classpath:/resources/images


  server:
    port: 8080


