
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-data-demo
    username: postgres
    password: P@ssw0rd

  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8082

mvc:
  pathmatch:
    matching-strategy: ant_path_matcher
